### ISSUE TITLE
IPv6 can't be saved into db

### ISSUE THREAD

**Issue by jakubsuchybio** [dmzx/phpBB-3.2-Unique-Visits-Counter#1]
Hi,
one of our admin have IPv6 static IP and get this error:
```
SQL ERROR [ mysql4 ]
Data too long for column 'uvc_ip' at row 1 [1406]
```

I see, that in repo you already fixed this issue with having varchar(40) for uvc_ip, could you please release that version publicly? 
Thx

**Comment by dmzx** [comment]
Uploaded it to phpBB.com
